# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
sort_sensitive = true
linemode = "size"
show_hidden = true

[preview]
image_filter = "triangle"
image_quality = 75
sixel_fraction = 15
ueberzug_scale = 1
ueberzug_offset = [0, 0, 0, 0]

[opener]
edit = [
  { run = 'kitty -- nvim "$@"', desc = "nvim", block = true, for = "unix", orphan = true },
  { run = 'code "%*"', orphan = true, for = "windows" },
]
open = [
  { run = 'open "$@"', desc = "Open", for = "linux" },
  { run = 'sh ~/.local/share/bin/swwwallpaper.sh -s "$@"', desc = "Set Wallpaper", for = "linux", orphan = true },
  { run = 'open "$@"', desc = "Open", for = "macos" },
  { run = 'start "" "%1"', orphan = true, desc = "Open", for = "windows" },
]
reveal = [
  { run = 'open -R "$1"', desc = "Reveal", for = "macos" },
  { run = 'explorer /select, "%1"', orphan = true, desc = "Reveal", for = "windows" },
  { run = '''exiftool "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show EXIF", for = "unix" },
]
extract = [
  { run = 'unar "$1"', desc = "Extract here", for = "unix" },
  { run = 'unar "%1"', desc = "Extract here", for = "windows" },
]
play = [
  { run = 'mpv "$@"', orphan = true, for = "unix" },
  { run = 'videocut "$@"', orphan = true, for = "unix" },
  { run = 'sh ~/.local/share/bin/set_video_wallpaper.sh "$@"', desc = "Wallpaper", orphan = true, for = "unix" },
  { run = 'mpv "%1"', orphan = true, for = "windows" },
  { run = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show media info", for = "unix" },
]


[input]
# cd
cd_offset = [0, 18, 50, 3]

# create
create_offset = [0, 18, 50, 3]

# trash
trash_offset = [0, 18, 50, 3]

# delete
delete_offset = [0, 18, 50, 3]

# filter
filter_offset = [0, 18, 50, 3]

# find
find_offset = [0, 18, 50, 3]

# search
search_offset = [0, 18, 50, 3]

# shell
shell_offset = [0, 18, 50, 3]

# overwrite
overwrite_offset = [0, 18, 50, 3]

# quit
quit_offset = [0, 18, 50, 3]
